### ISSUE TITLE
Error running the script

### ISSUE THREAD

**Issue by geeflaxx** [prithugoswami/auto-movie-tagger#13]
I searched over 5 hours to look at the script like this. 

Every project just have his own Database, but nothing change the file.

Thanks! For creating this project.

I got following Error:

Traceback (most recent call last):
  File "/home/patrick/PycharmProjects/LearnHacking/test.py", line 23, in <module>
    from imdbpie import Imdb
  File "/home/patrick/PycharmProjects/LearnHacking/venv/lib/python3.10/site-packages/imdbpie/__init__.py", line 2, in <module>
    from .imdbpie import Imdb  # noqa
  File "/home/patrick/PycharmProjects/LearnHacking/venv/lib/python3.10/site-packages/imdbpie/imdbpie.py", line 17, in <module>
    from .auth import Auth
  File "/home/patrick/PycharmProjects/LearnHacking/venv/lib/python3.10/site-packages/imdbpie/auth.py", line 13, in <module>
    import diskcache
  File "/home/patrick/PycharmProjects/LearnHacking/venv/lib/python3.10/site-packages/diskcache/__init__.py", line 5, in <module>
    from .fanout import FanoutCache
  File "/home/patrick/PycharmProjects/LearnHacking/venv/lib/python3.10/site-packages/diskcache/fanout.py", line 10, in <module>
    from .persistent import Deque, Index
  File "/home/patrick/PycharmProjects/LearnHacking/venv/lib/python3.10/site-packages/diskcache/persistent.py", line 8, in <module>
    from collections import MutableMapping, OrderedDict, Sequence
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

What shall I change?

**Comment by geeflaxx** [comment]
Change imports in the the "persistent.py" in path: python3.10/site-packages/diskcache/persistent.py

to

from collections.abc import MutableMapping,Sequence, KeysView, ValuesView, ItemsView
from collections import OrderedDict


thanks for your work
